version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: ${DATABASE_PORT}
            user: ${DATABASE_USER}
            password: ${DATABASE_PASSWORD}
            managementSchema: management
            database: issue_prisma_binding
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - prisma
      - postgres
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/
    ports:
    - 4000:4000
    volumes:
    - .:/usr/src/app
volumes:
  postgres: